Script started on 2015年03月17日 (週二) 00時41分03秒
]0;F74004046@2015cpp: ~/lab1/lab1F74004046@2015cpp:~/lab1/lab1$ vim lab1.scriptls[Kgit clone https://github.com/CBAlex/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[Klone https://github.com/CBAlex/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cls[Kvim lab1.script[Kvim lab1.scriptls[Kgit clone https://github.com/CBAlex/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[3Pwhoami;pwdgit config -l[K[K[K[K[K[K[K[K[K[K[K[K[Kg++ -o lab2[K1 lab2[K1.cpp
]0;F74004046@2015cpp: ~/lab1/lab1F74004046@2015cpp:~/lab1/lab1$ ./lab1
please enter a integer: 22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;F74004046@2015cpp: ~/lab1/lab1F74004046@2015cpp:~/lab1/lab1$ exit

Script done on 2015年03月17日 (週二) 00時41分55秒
